AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for API Gateway and Lambda integration tests'

Resources:
  # Lambda Functions
  ParseAndReturnBodyLambdaFunction:
    # ... existing configuration ...

  ReturnRawBodyLambdaFunction:
    # ... existing configuration ...

  ReturnFullEventLambdaFunction:
    # ... existing configuration ...

  # Single REST API Gateway
  MainRestApi:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Name: !Sub '${AWS::StackName}-MainRestAPI'
      EndpointConfiguration:
        Types:
          - REGIONAL
      BinaryMediaTypes:
        - '*/*'

  MainRestApiDeployment:
    Type: 'AWS::ApiGateway::Deployment'
    Properties:
      RestApiId: !Ref MainRestApi
      StageName: 'test'

  # Single HTTP API v1
  MainHttpApiV1:
    Type: 'AWS::ApiGatewayV2::Api'
    Properties:
      Name: !Sub '${AWS::StackName}-MainHttpAPIv1'
      ProtocolType: HTTP

  MainHttpV1Stage:
    Type: 'AWS::ApiGatewayV2::Stage'
    Properties:
      ApiId: !Ref MainHttpApiV1
      StageName: '$default'
      AutoDeploy: true

  # Single HTTP API v2
  MainHttpApiV2:
    Type: 'AWS::ApiGatewayV2::Api'
    Properties:
      Name: !Sub '${AWS::StackName}-MainHttpAPIv2'
      ProtocolType: HTTP

  MainHttpV2Stage:
    Type: 'AWS::ApiGatewayV2::Stage'
    Properties:
      ApiId: !Ref MainHttpApiV2
      StageName: '$default'
      AutoDeploy: true

Outputs:
  MainRestApiId:
    Value: !Ref MainRestApi
  MainHttpApiV1Id:
    Value: !Ref MainHttpApiV1
  MainHttpApiV2Id:
    Value: !Ref MainHttpApiV2
  # ... Lambda ARN outputs ... 