version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 3.1
  build:
    commands:
      - pwsh LambdaRuntimeDockerfiles/dotnet5/Infrastructure/src/Infrastructure/DockerPush/build.ps1
        -SourceEcr $AWS_LAMBDA_SOURCE_ECR
        -EcrRepositoryName $AWS_LAMBDA_ECR_REPOSITORY_NAME
        -SourceImageTag $CODEBUILD_RESOLVED_SOURCE_VERSION
        -DestinationEcrs $AWS_LAMBDA_DESTINATION_ECRS
        -DestinationImageTag $AWS_LAMBDA_DESTINATION_IMAGE_TAG
