// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

namespace Amazon.Lambda.DurableExecution;

/// <summary>
/// A pending callback created by
/// <see cref="IDurableContext.CreateCallbackAsync{T}(string?, CallbackConfig?, System.Threading.CancellationToken)"/>.
/// Hands back a <see cref="CallbackId"/> for external systems to use, plus a
/// <see cref="GetResultAsync(System.Threading.CancellationToken)"/> hook that
/// suspends the workflow until the external system completes the callback.
/// </summary>
/// <typeparam name="T">The callback result type.</typeparam>
public interface ICallback<T>
{
    /// <summary>
    /// The callback ID generated by the durable execution service. External
    /// systems pass this ID to <c>SendDurableExecutionCallbackSuccess</c> /
    /// <c>SendDurableExecutionCallbackFailure</c> /
    /// <c>SendDurableExecutionCallbackHeartbeat</c> to deliver a result.
    /// </summary>
    string CallbackId { get; }

    /// <summary>
    /// Suspends the workflow until the callback is completed, then returns the
    /// deserialized result.
    /// </summary>
    /// <remarks>
    /// On the first invocation that reaches this call, the workflow suspends
    /// (Lambda terminates). When the external system completes the callback
    /// the service re-invokes Lambda; this call then returns the cached result
    /// without re-executing user code.
    /// </remarks>
    /// <exception cref="CallbackFailedException">
    /// Thrown when the external system reported a failure result.
    /// </exception>
    /// <exception cref="CallbackTimeoutException">
    /// Thrown when the service timed out the callback (overall timeout or
    /// heartbeat timeout elapsed).
    /// </exception>
    Task<T> GetResultAsync(CancellationToken cancellationToken = default);
}
