version: 0.2
phases:
  pre_build:
    commands:
      # Find and delete the global.json files that were added by CodeBuild. This causes issues when multiple SDKs are installed.
      - find / -type f -name 'global.json' -delete
      - |
        if [ "$AWS_LAMBDA_DOTNET_SDK_VERSION" = "" ]; then
          curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel $AWS_LAMBDA_DOTNET_FRAMEWORK_CHANNEL
        else
          curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --version $AWS_LAMBDA_DOTNET_SDK_VERSION
        fi
      - export PATH="$PATH:$HOME/.dotnet"
      - export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
      - rm -rf /usr/bin/pwsh
      - dotnet tool install --global PowerShell --version $AWS_LAMBDA_POWERSHELL_VERSION
  build:
    commands:
      - pwsh LambdaRuntimeDockerfiles/Infrastructure/src/Infrastructure/DockerBuild/build.ps1
        -StageEcr $AWS_LAMBDA_STAGE_ECR
        -EcrRepositoryName $AWS_LAMBDA_ECR_REPOSITORY_NAME
        -ImageTag $AWS_LAMBDA_IMAGE_TAG
        -Architecture $AWS_LAMBDA_ARCHITECTURE
        -Framework $AWS_LAMBDA_DOTNET_FRAMEWORK_VERSION
