// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Amazon.Lambda.Annotations.SourceGenerator.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Amazon.Lambda.Annotations.SourceGenerator.Extensions;
    using Amazon.Lambda.Annotations.SourceGenerator.Models;
    using Amazon.Lambda.Annotations.SourceGenerator.Models.Attributes;
    using System;

    /// <summary>
    /// Class to produce the template output
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public partial class ALBSetupParameters : ALBSetupParametersBase
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {

        ParameterSignature = string.Join(", ", _model.LambdaMethod.Parameters
            .Select(p =>
            {
                // Pass the same context parameter for ILambdaContext that comes from the generated method.
                if (p.Type.FullName == TypeFullNames.ILambdaContext)
                {
                    return "__context__";
                }

                // Pass the same request parameter for ALB Request Type that comes from the generated method.
                if (TypeFullNames.ALBRequests.Contains(p.Type.FullName))
                {
                    return "__request__";
                }

                return p.Name;
            }));

        var albApiAttribute = _model.LambdaMethod.Attributes.FirstOrDefault(att => att.Type.FullName == TypeFullNames.ALBApiAttribute) as AttributeModel<Amazon.Lambda.Annotations.ALB.ALBApiAttribute>;

        // Determine whether multi-value headers are enabled
        var useMultiValue = albApiAttribute?.Data?.IsMultiValueHeadersSet == true && albApiAttribute.Data.MultiValueHeaders;

        if (_model.LambdaMethod.Parameters.HasConvertibleParameter())
        {

            this.Write("            var validationErrors = new List<string>();\r\n\r\n");

        }

        foreach (var parameter in _model.LambdaMethod.Parameters)
        {
            if (parameter.Type.FullName == TypeFullNames.ILambdaContext || TypeFullNames.ALBRequests.Contains(parameter.Type.FullName))
            {
                // No action required for ILambdaContext and ALB RequestType, they are passed from the generated method parameter directly to the original method.
            }
            else if (parameter.Attributes.Any(att => att.Type.FullName == TypeFullNames.FromServiceAttribute))
            {

            this.Write("            var ");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name));
            this.Write(" = scope.ServiceProvider.GetRequiredService<");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Type.FullName));
            this.Write(">();\r\n");

            }
            else if (parameter.Attributes.Any(att => att.Type.FullName == TypeFullNames.ALBFromQueryAttribute))
            {
                var fromQueryAttribute = parameter.Attributes.First(att => att.Type.FullName == TypeFullNames.ALBFromQueryAttribute) as AttributeModel<Amazon.Lambda.Annotations.ALB.FromQueryAttribute>;

                // Use parameter name as key, if Name has not specified explicitly in the attribute definition.
                var parameterKey = fromQueryAttribute?.Data?.Name ?? parameter.Name;

                var queryStringParameters = useMultiValue ? "MultiValueQueryStringParameters" : "QueryStringParameters";

            this.Write("            var ");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name));
            this.Write(" = default(");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Type.FullName));
            this.Write(");\r\n");

                if (parameter.Type.IsEnumerable && parameter.Type.IsGenericType)
                {
                    if (useMultiValue)
                    {
                        // Multi-value mode: MultiValueQueryStringParameters is IDictionary<string, IList<string>>
                        if (parameter.Type.TypeArguments.Count != 1)
                        {
                            throw new NotSupportedException("Only one type argument is supported for generic types.");
                        }

                        var typeArgument = parameter.Type.TypeArguments.First();
            this.Write("            if (__request__.");
            this.Write(this.ToStringHelper.ToStringWithCulture(queryStringParameters));
            this.Write("?.ContainsKey(\"");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameterKey));
            this.Write("\") == true)\r\n            {\r\n                ");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name));
            this.Write(" = __request__.");
            this.Write(this.ToStringHelper.ToStringWithCulture(queryStringParameters));
            this.Write("[\"");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameterKey));
            this.Write("\"]\r\n                    .Select(q =>\r\n                    {\r\n                        try\r\n                        {\r\n                            return (");
            this.Write(this.ToStringHelper.ToStringWithCulture(typeArgument.FullName));
            this.Write(")Convert.ChangeType(q, typeof(");
            this.Write(this.ToStringHelper.ToStringWithCulture(typeArgument.FullNameWithoutAnnotations));
            this.Write("));\r\n                        }\r\n                        catch (Exception e) when (e is InvalidCastException || e is FormatException || e is OverflowException || e is ArgumentException)\r\n                        {\r\n                            validationErrors.Add($\"Value {q} at \'");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameterKey));
            this.Write("\' failed to satisfy constraint: {e.Message}\");\r\n                            return default;\r\n                        }\r\n                    })\r\n                    .ToList();\r\n            }\r\n\r\n");

                    }
                    else
                    {
                        // Single-value mode: QueryStringParameters is IDictionary<string, string>
                        // Split by comma to support multiple values
                        if (parameter.Type.TypeArguments.Count != 1)
                        {
                            throw new NotSupportedException("Only one type argument is supported for generic types.");
                        }

                        var typeArgument = parameter.Type.TypeArguments.First();
            this.Write("            if (__request__.");
            this.Write(this.ToStringHelper.ToStringWithCulture(queryStringParameters));
            this.Write("?.ContainsKey(\"");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameterKey));
            this.Write("\") == true)\r\n            {\r\n                ");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name));
            this.Write(" = __request__.");
            this.Write(this.ToStringHelper.ToStringWithCulture(queryStringParameters));
            this.Write("[\"");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameterKey));
            this.Write("\"].Split(\",\")\r\n                    .Select(q =>\r\n                    {\r\n                        try\r\n                        {\r\n                            return (");
            this.Write(this.ToStringHelper.ToStringWithCulture(typeArgument.FullName));
            this.Write(")Convert.ChangeType(q, typeof(");
            this.Write(this.ToStringHelper.ToStringWithCulture(typeArgument.FullNameWithoutAnnotations));
            this.Write("));\r\n                        }\r\n                        catch (Exception e) when (e is InvalidCastException || e is FormatException || e is OverflowException || e is ArgumentException)\r\n                        {\r\n                            validationErrors.Add($\"Value {q} at \'");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameterKey));
            this.Write("\' failed to satisfy constraint: {e.Message}\");\r\n                            return default;\r\n                        }\r\n                    })\r\n                    .ToList();\r\n            }\r\n\r\n");

                    }
                }
                else
                {
                    // Non-generic types are mapped directly to the target parameter.
            this.Write("            if (__request__.");
            this.Write(this.ToStringHelper.ToStringWithCulture(queryStringParameters));
            this.Write("?.ContainsKey(\"");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameterKey));
            this.Write("\") == true)\r\n            {\r\n                try\r\n                {\r\n                    ");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name));
            this.Write(" = (");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Type.FullName));
            this.Write(")Convert.ChangeType(__request__.");
            this.Write(this.ToStringHelper.ToStringWithCulture(queryStringParameters));
            this.Write("[\"");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameterKey));
            this.Write("\"], typeof(");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Type.FullNameWithoutAnnotations));
            this.Write("));\r\n                }\r\n                catch (Exception e) when (e is InvalidCastException || e is FormatException || e is OverflowException || e is ArgumentException)\r\n                {\r\n                    validationErrors.Add($\"Value {__request__.");
            this.Write(this.ToStringHelper.ToStringWithCulture(queryStringParameters));
            this.Write("[\"");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameterKey));
            this.Write("\"]} at \'");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameterKey));
            this.Write("\' failed to satisfy constraint: {e.Message}\");\r\n                }\r\n            }\r\n\r\n");

                }

            }
            else if (parameter.Attributes.Any(att => att.Type.FullName == TypeFullNames.ALBFromHeaderAttribute))
            {
                var fromHeaderAttribute =
                    parameter.Attributes.First(att => att.Type.FullName == TypeFullNames.ALBFromHeaderAttribute) as
                        AttributeModel<Amazon.Lambda.Annotations.ALB.FromHeaderAttribute>;

                // Use parameter name as key, if Name has not specified explicitly in the attribute definition.
                var headerKey = fromHeaderAttribute?.Data?.Name ?? parameter.Name;

                var headers = useMultiValue ? "MultiValueHeaders" : "Headers";

            this.Write("            var ");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name));
            this.Write(" = default(");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Type.FullName));
            this.Write(");\r\n");

                if (parameter.Type.IsEnumerable && parameter.Type.IsGenericType)
                {
                    if (useMultiValue)
                    {
                        // Multi-value mode: MultiValueHeaders is IDictionary<string, IList<string>>
                        if (parameter.Type.TypeArguments.Count != 1)
                        {
                            throw new NotSupportedException("Only one type argument is supported for generic types.");
                        }

                        var typeArgument = parameter.Type.TypeArguments.First();
            this.Write("            if (__request__.");
            this.Write(this.ToStringHelper.ToStringWithCulture(headers));
            this.Write("?.Any(x => string.Equals(x.Key, \"");
            this.Write(this.ToStringHelper.ToStringWithCulture(headerKey));
            this.Write("\", StringComparison.OrdinalIgnoreCase)) == true)\r\n            {\r\n                ");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name));
            this.Write(" = __request__.");
            this.Write(this.ToStringHelper.ToStringWithCulture(headers));
            this.Write(".First(x => string.Equals(x.Key, \"");
            this.Write(this.ToStringHelper.ToStringWithCulture(headerKey));
            this.Write("\", StringComparison.OrdinalIgnoreCase)).Value\r\n                    .Select(q =>\r\n                    {\r\n                        try\r\n                        {\r\n                            return (");
            this.Write(this.ToStringHelper.ToStringWithCulture(typeArgument.FullName));
            this.Write(")Convert.ChangeType(q, typeof(");
            this.Write(this.ToStringHelper.ToStringWithCulture(typeArgument.FullNameWithoutAnnotations));
            this.Write("));\r\n                        }\r\n                        catch (Exception e) when (e is InvalidCastException || e is FormatException || e is OverflowException || e is ArgumentException)\r\n                        {\r\n                            validationErrors.Add($\"Value {q} at \'");
            this.Write(this.ToStringHelper.ToStringWithCulture(headerKey));
            this.Write("\' failed to satisfy constraint: {e.Message}\");\r\n                            return default;\r\n                        }\r\n                    })\r\n                    .ToList();\r\n            }\r\n\r\n");

                    }
                    else
                    {
                        // Single-value mode: Headers is IDictionary<string, string>
                        // Split by comma to support multiple values
                        if (parameter.Type.TypeArguments.Count != 1)
                        {
                            throw new NotSupportedException("Only one type argument is supported for generic types.");
                        }

                        var typeArgument = parameter.Type.TypeArguments.First();
            this.Write("            if (__request__.");
            this.Write(this.ToStringHelper.ToStringWithCulture(headers));
            this.Write("?.Any(x => string.Equals(x.Key, \"");
            this.Write(this.ToStringHelper.ToStringWithCulture(headerKey));
            this.Write("\", StringComparison.OrdinalIgnoreCase)) == true)\r\n            {\r\n                ");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name));
            this.Write(" = __request__.");
            this.Write(this.ToStringHelper.ToStringWithCulture(headers));
            this.Write(".First(x => string.Equals(x.Key, \"");
            this.Write(this.ToStringHelper.ToStringWithCulture(headerKey));
            this.Write("\", StringComparison.OrdinalIgnoreCase)).Value.Split(\",\")\r\n                    .Select(q =>\r\n                    {\r\n                        try\r\n                        {\r\n                            return (");
            this.Write(this.ToStringHelper.ToStringWithCulture(typeArgument.FullName));
            this.Write(")Convert.ChangeType(q, typeof(");
            this.Write(this.ToStringHelper.ToStringWithCulture(typeArgument.FullNameWithoutAnnotations));
            this.Write("));\r\n                        }\r\n                        catch (Exception e) when (e is InvalidCastException || e is FormatException || e is OverflowException || e is ArgumentException)\r\n                        {\r\n                            validationErrors.Add($\"Value {q} at \'");
            this.Write(this.ToStringHelper.ToStringWithCulture(headerKey));
            this.Write("\' failed to satisfy constraint: {e.Message}\");\r\n                            return default;\r\n                        }\r\n                    })\r\n                    .ToList();\r\n            }\r\n\r\n");

                    }
                }
                else
                {
                    // Non-generic types are mapped directly to the target parameter.
            this.Write("            if (__request__.");
            this.Write(this.ToStringHelper.ToStringWithCulture(headers));
            this.Write("?.Any(x => string.Equals(x.Key, \"");
            this.Write(this.ToStringHelper.ToStringWithCulture(headerKey));
            this.Write("\", StringComparison.OrdinalIgnoreCase)) == true)\r\n            {\r\n                try\r\n                {\r\n                    ");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name));
            this.Write(" = (");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Type.FullName));
            this.Write(")Convert.ChangeType(__request__.");
            this.Write(this.ToStringHelper.ToStringWithCulture(headers));
            this.Write(".First(x => string.Equals(x.Key, \"");
            this.Write(this.ToStringHelper.ToStringWithCulture(headerKey));
            this.Write("\", StringComparison.OrdinalIgnoreCase)).Value, typeof(");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Type.FullNameWithoutAnnotations));
            this.Write("));\r\n                }\r\n                catch (Exception e) when (e is InvalidCastException || e is FormatException || e is OverflowException || e is ArgumentException)\r\n                {\r\n                    validationErrors.Add($\"Value {__request__.");
            this.Write(this.ToStringHelper.ToStringWithCulture(headers));
            this.Write(".First(x => string.Equals(x.Key, \"");
            this.Write(this.ToStringHelper.ToStringWithCulture(headerKey));
            this.Write("\", StringComparison.OrdinalIgnoreCase)).Value} at \'");
            this.Write(this.ToStringHelper.ToStringWithCulture(headerKey));
            this.Write("\' failed to satisfy constraint: {e.Message}\");\r\n                }\r\n            }\r\n\r\n");

                }
            }
            else if (parameter.Attributes.Any(att => att.Type.FullName == TypeFullNames.ALBFromBodyAttribute))
            {
                // string parameter does not need to be de-serialized
                if (parameter.Type.IsString())
                {

            this.Write("            var ");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name));
            this.Write(" = __request__.Body;\r\n\r\n");

                }
                else
                {

            this.Write("            var ");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name));
            this.Write(" = default(");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Type.FullName));
            this.Write(");\r\n            try\r\n            {\r\n                // convert string to stream\r\n                var byteArray = Encoding.UTF8.GetBytes(__request__.Body);\r\n                var stream = new MemoryStream(byteArray);\r\n                ");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name));
            this.Write(" = serializer.Deserialize<");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Type.FullName));
            this.Write(">(stream);\r\n            }\r\n            catch (Exception e)\r\n            {\r\n                validationErrors.Add($\"Value {__request__.Body} at \'body\' failed to satisfy constraint: {e.Message}\");\r\n            }\r\n\r\n");

                }
            }
            else
            {
                throw new NotSupportedException($"{parameter.Name} parameter of type {parameter.Type.FullName} passing is not supported for ALB functions. Use [FromHeader], [FromQuery], [FromBody], or [FromServices] attributes.");
            }
        }

        if (_model.LambdaMethod.Parameters.HasConvertibleParameter())
        {

            this.Write("            // return 400 Bad Request if there exists a validation error\r\n" +
                "            if (validationErrors.Any())\r\n" +
                "            {\r\n" +
                "                var errorResult = new Amazon.Lambda.ApplicationLoadBalancerEvents.ApplicationLoadBalancerResponse\r\n" +
                "                {\r\n" +
                "                    Body = @$\"{{\"\"message\"\": \"\"{validationErrors.Count} validation error(s) detected: {string.Join(\",\", validationErrors)}\"\"}}\",\r\n" +
                "                    Headers = new Dictionary<string, string>\r\n" +
                "                    {\r\n" +
                "                        {\"Content-Type\", \"application/json\"}\r\n" +
                "                    },\r\n" +
                "                    StatusCode = 400\r\n" +
                "                };\r\n" +
                "                return errorResult;\r\n" +
                "            }\r\n\r\n");

        }

            return this.GenerationEnvironment.ToString();
        }
    }

    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public class ALBSetupParametersBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            if (((this.GenerationEnvironment.Length == 0)
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
