// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Amazon.Lambda.Annotations.SourceGenerator.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Amazon.Lambda.Annotations.SourceGenerator.Extensions;
    using Amazon.Lambda.Annotations.SourceGenerator.Models;
    using Amazon.Lambda.Annotations.SourceGenerator.Models.Attributes;
    using System;
    
    public partial class AuthorizerSetupParameters : AuthorizerSetupParametersBase
    {
        public virtual string TransformText()
        {
        // Build the parameter signature for calling the user's method
        ParameterSignature = string.Join(", ", _model.LambdaMethod.Parameters
            .Select(p =>
            {
                // Pass the same context parameter for ILambdaContext that comes from the generated method.
                if (p.Type.FullName == TypeFullNames.ILambdaContext)
                {
                    return "__context__";
                }

                // Pass the same request parameter for Request Type that comes from the generated method.
                if (TypeFullNames.Requests.Contains(p.Type.FullName))
                {
                    return "__request__";
                }

                return p.Name;
            }));

        var httpApiAuthorizerAttribute = _model.LambdaMethod.Attributes.FirstOrDefault(att => att.Type.FullName == TypeFullNames.HttpApiAuthorizerAttribute) as AttributeModel<Amazon.Lambda.Annotations.APIGateway.HttpApiAuthorizerAttribute>;
        var restApiAuthorizerAttribute = _model.LambdaMethod.Attributes.FirstOrDefault(att => att.Type.FullName == TypeFullNames.RestApiAuthorizerAttribute) as AttributeModel<Amazon.Lambda.Annotations.APIGateway.RestApiAuthorizerAttribute>;

        // Determine if the authorizer request type is V2 (has Headers as IDictionary<string,string>)
        var isV2Request = httpApiAuthorizerAttribute != null && httpApiAuthorizerAttribute.Data.AuthorizerPayloadFormatVersion == Amazon.Lambda.Annotations.APIGateway.AuthorizerPayloadFormatVersion.V2;

        foreach (var parameter in _model.LambdaMethod.Parameters)
        {
            if (parameter.Type.FullName == TypeFullNames.ILambdaContext || TypeFullNames.Requests.Contains(parameter.Type.FullName))
            {
                // No action required for ILambdaContext and RequestType, they are passed from the generated method parameter directly to the original method.
            }
            else if (parameter.Attributes.Any(att => att.Type.FullName == TypeFullNames.FromServiceAttribute))
            {
            this.Write("            var ");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name));
            this.Write(" = scope.ServiceProvider.GetRequiredService<");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Type.FullName));
            this.Write(">();\r\n");
            }
            else if (parameter.Attributes.Any(att => att.Type.FullName == TypeFullNames.FromHeaderAttribute))
            {
                var fromHeaderAttribute =
                    parameter.Attributes.First(att => att.Type.FullName == TypeFullNames.FromHeaderAttribute) as
                        AttributeModel<Amazon.Lambda.Annotations.APIGateway.FromHeaderAttribute>;

                // Use parameter name as key, if Name has not specified explicitly in the attribute definition.
                var headerKey = fromHeaderAttribute?.Data?.Name ?? parameter.Name;

            this.Write("            var ");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name));
            this.Write(" = default(");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Type.FullName));
            this.Write(");\r\n");
            this.Write("            if (__request__.Headers?.Any(x => string.Equals(x.Key, \"");
            this.Write(this.ToStringHelper.ToStringWithCulture(headerKey));
            this.Write("\", StringComparison.OrdinalIgnoreCase)) == true)\r\n");
            this.Write("            {\r\n");
            this.Write("                try\r\n");
            this.Write("                {\r\n");
            this.Write("                    ");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name));
            this.Write(" = (");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Type.FullName));
            this.Write(")Convert.ChangeType(__request__.Headers.First(x => string.Equals(x.Key, \"");
            this.Write(this.ToStringHelper.ToStringWithCulture(headerKey));
            this.Write("\", StringComparison.OrdinalIgnoreCase)).Value, typeof(");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Type.FullNameWithoutAnnotations));
            this.Write("));\r\n");
            this.Write("                }\r\n");
            this.Write("                catch (Exception e) when (e is InvalidCastException || e is FormatException || e is OverflowException || e is ArgumentException)\r\n");
            this.Write("                {\r\n");
            this.Write("                    __context__.Logger.Log($\"Failed to extract header '");
            this.Write(this.ToStringHelper.ToStringWithCulture(headerKey));
            this.Write("': {e.Message}\");\r\n");
            this.Write("                }\r\n");
            this.Write("            }\r\n\r\n");
            }
            else if (parameter.Attributes.Any(att => att.Type.FullName == TypeFullNames.FromQueryAttribute))
            {
                var fromQueryAttribute = parameter.Attributes.First(att => att.Type.FullName == TypeFullNames.FromQueryAttribute) as AttributeModel<Amazon.Lambda.Annotations.APIGateway.FromQueryAttribute>;
                var parameterKey = fromQueryAttribute?.Data?.Name ?? parameter.Name;

            this.Write("            var ");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name));
            this.Write(" = default(");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Type.FullName));
            this.Write(");\r\n");
            this.Write("            if (__request__.QueryStringParameters?.ContainsKey(\"");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameterKey));
            this.Write("\") == true)\r\n");
            this.Write("            {\r\n");
            this.Write("                try\r\n");
            this.Write("                {\r\n");
            this.Write("                    ");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name));
            this.Write(" = (");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Type.FullName));
            this.Write(")Convert.ChangeType(__request__.QueryStringParameters[\"");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameterKey));
            this.Write("\"], typeof(");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Type.FullNameWithoutAnnotations));
            this.Write("));\r\n");
            this.Write("                }\r\n");
            this.Write("                catch (Exception e) when (e is InvalidCastException || e is FormatException || e is OverflowException || e is ArgumentException)\r\n");
            this.Write("                {\r\n");
            this.Write("                    __context__.Logger.Log($\"Failed to extract query parameter '");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameterKey));
            this.Write("': {e.Message}\");\r\n");
            this.Write("                }\r\n");
            this.Write("            }\r\n\r\n");
            }
            else if (parameter.Attributes.Any(att => att.Type.FullName == TypeFullNames.FromRouteAttribute))
            {
                var fromRouteAttribute = parameter.Attributes?.FirstOrDefault(att => att.Type.FullName == TypeFullNames.FromRouteAttribute) as AttributeModel<Amazon.Lambda.Annotations.APIGateway.FromRouteAttribute>;
                var routeKey = fromRouteAttribute?.Data?.Name ?? parameter.Name;

            this.Write("            var ");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name));
            this.Write(" = default(");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Type.FullName));
            this.Write(");\r\n");
            this.Write("            if (__request__.PathParameters?.ContainsKey(\"");
            this.Write(this.ToStringHelper.ToStringWithCulture(routeKey));
            this.Write("\") == true)\r\n");
            this.Write("            {\r\n");
            this.Write("                try\r\n");
            this.Write("                {\r\n");
            this.Write("                    ");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name));
            this.Write(" = (");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Type.FullName));
            this.Write(")Convert.ChangeType(__request__.PathParameters[\"");
            this.Write(this.ToStringHelper.ToStringWithCulture(routeKey));
            this.Write("\"], typeof(");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Type.FullNameWithoutAnnotations));
            this.Write("));\r\n");
            this.Write("                }\r\n");
            this.Write("                catch (Exception e) when (e is InvalidCastException || e is FormatException || e is OverflowException || e is ArgumentException)\r\n");
            this.Write("                {\r\n");
            this.Write("                    __context__.Logger.Log($\"Failed to extract route parameter '");
            this.Write(this.ToStringHelper.ToStringWithCulture(routeKey));
            this.Write("': {e.Message}\");\r\n");
            this.Write("                }\r\n");
            this.Write("            }\r\n\r\n");
            }
            else
            {
                throw new NotSupportedException($"{parameter.Name} parameter of type {parameter.Type.FullName} passing is not supported for authorizer functions.");
            }
        }

            return this.GenerationEnvironment.ToString();
        }
    }

    #region Base class
    public class AuthorizerSetupParametersBase
    {
        private global::System.Text.StringBuilder generationEnvironmentField;
        private bool endsWithNewline;
        
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }

        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            this.GenerationEnvironment.Append(textToAppend);
        }

        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }

        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField = global::System.Globalization.CultureInfo.InvariantCulture;
            
            public System.IFormatProvider FormatProvider
            {
                get { return this.formatProviderField; }
                set { if ((value != null)) { this.formatProviderField = value; } }
            }

            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] { typeof(System.IFormatProvider) });
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] { this.formatProviderField })));
                }
            }
        }

        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();

        public ToStringInstanceHelper ToStringHelper
        {
            get { return this.toStringHelperField; }
        }
    }
    #endregion
}
