// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Amazon.Lambda.Annotations.SourceGenerator.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Amazon.Lambda.Annotations.SourceGenerator.Extensions;
    using Amazon.Lambda.Annotations.SourceGenerator.Models;
    using Amazon.Lambda.Annotations.SourceGenerator.Models.Attributes;
    using System;

    public partial class AuthorizerInvoke : AuthorizerInvokeBase
    {
        public virtual string TransformText()
        {
        var hasHttpApiAuthorizer = _model.LambdaMethod.Attributes.Any(att => att.Type.FullName == TypeFullNames.HttpApiAuthorizerAttribute);
        var hasRestApiAuthorizer = _model.LambdaMethod.Attributes.Any(att => att.Type.FullName == TypeFullNames.RestApiAuthorizerAttribute);

        // Determine if the generated handler uses V2 request type based on the request parameter
        var isV2Request = _model.GeneratedMethod.Parameters.Any(p => p.Type.FullName == TypeFullNames.APIGatewayCustomAuthorizerV2Request);

        if (_model.LambdaMethod.ReturnsIAuthorizerResult)
        {
            // Determine the serialization format based on the authorizer attribute
            // For HTTP API, we need to check EnableSimpleResponses from the attribute data
            string format;
            if (hasHttpApiAuthorizer && isV2Request)
            {
                // V2 with simple responses (the most common HTTP API case)
                format = "AuthorizerResultSerializationOptions.AuthorizerFormat.HttpApiSimple";
            }
            else if (hasHttpApiAuthorizer)
            {
                // V1 HTTP API uses IAM policy format
                format = "AuthorizerResultSerializationOptions.AuthorizerFormat.HttpApiIamPolicy";
            }
            else
            {
                format = "AuthorizerResultSerializationOptions.AuthorizerFormat.RestApi";
            }

            // V2 uses RouteArn, V1/REST uses MethodArn
            var methodArnExpression = isV2Request ? "__request__.RouteArn" : "__request__.MethodArn";

            this.Write("            var authorizerResult = ");
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.LambdaMethod.ReturnsGenericTask ? "await " : ""));
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.LambdaMethod.ContainingType.Name.ToCamelCase()));
            this.Write(".");
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.LambdaMethod.Name));
            this.Write("(");
            this.Write(this.ToStringHelper.ToStringWithCulture(_parameterSignature));
            this.Write(");\r\n");
            this.Write("            var serializationOptions = new AuthorizerResultSerializationOptions\r\n");
            this.Write("            {\r\n");
            this.Write("                Format = ");
            this.Write(this.ToStringHelper.ToStringWithCulture(format));
            this.Write(",\r\n");
            this.Write("                MethodArn = ");
            this.Write(this.ToStringHelper.ToStringWithCulture(methodArnExpression));
            this.Write("\r\n");
            this.Write("            };\r\n");
            this.Write("            var response = (System.IO.Stream)authorizerResult.Serialize(serializationOptions);\r\n");
            this.Write("            return response;\r\n");
        }
        else
        {
            // Raw return type - pass through directly (backwards compatibility)
            this.Write("            var response = ");
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.LambdaMethod.ReturnsGenericTask ? "await " : ""));
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.LambdaMethod.ContainingType.Name.ToCamelCase()));
            this.Write(".");
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.LambdaMethod.Name));
            this.Write("(");
            this.Write(this.ToStringHelper.ToStringWithCulture(_parameterSignature));
            this.Write(");\r\n");
            this.Write("            return response;\r\n");
        }

            return this.GenerationEnvironment.ToString();
        }
    }

    #region Base class
    public class AuthorizerInvokeBase
    {
        private global::System.Text.StringBuilder generationEnvironmentField;
        private bool endsWithNewline;

        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }

        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            this.GenerationEnvironment.Append(textToAppend);
        }

        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }

        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField = global::System.Globalization.CultureInfo.InvariantCulture;

            public System.IFormatProvider FormatProvider
            {
                get { return this.formatProviderField; }
                set { if ((value != null)) { this.formatProviderField = value; } }
            }

            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] { typeof(System.IFormatProvider) });
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] { this.formatProviderField })));
                }
            }
        }

        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();

        public ToStringInstanceHelper ToStringHelper
        {
            get { return this.toStringHelperField; }
        }
    }
    #endregion
}
