// <auto-generated/>

using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;
using System.IO;
using Amazon.Lambda.Core;

namespace TestServerlessApp.DurableExecutionExamples;

public class GeneratedProgram
{
    /// <summary>
    /// This is responsible for inspecting the 'ANNOTATIONS_HANDLER' environment variable and invoking the appropriate Lambda function handler.
    /// </summary>
    public static async Task Main(string[] args)
    {

        switch (Environment.GetEnvironmentVariable("ANNOTATIONS_HANDLER"))
        {
            case "ProcessOrder":
                Func<Amazon.Lambda.DurableExecution.DurableExecutionInvocationInput, Amazon.Lambda.Core.ILambdaContext, System.Threading.Tasks.Task<Amazon.Lambda.DurableExecution.DurableExecutionInvocationOutput>> processorder_handler = new TestServerlessApp.DurableExecutionExamples.ValidDurableExecution_ProcessOrder_Generated().ProcessOrder;
                await Amazon.Lambda.RuntimeSupport.LambdaBootstrapBuilder.Create(processorder_handler, new Amazon.Lambda.Serialization.SystemTextJson.DefaultLambdaJsonSerializer()).Build().RunAsync();
                break;

        }
    }
}