// <auto-generated/>

using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;
using System.IO;
using Amazon.Lambda.Core;

namespace TestServerlessApp
{
    public class ParameterlessTaskMethods_NoParameterTask_Generated
    {
        private readonly ParameterlessTaskMethods parameterlessTaskMethods;
        private readonly Amazon.Lambda.Serialization.SystemTextJson.DefaultLambdaJsonSerializer serializer;

        /// <summary>
        /// Default constructor. This constructor is used by Lambda to construct the instance. When invoked in a Lambda environment
        /// the AWS credentials will come from the IAM role associated with the function and the AWS region will be set to the
        /// region the Lambda function is executed in.
        /// </summary>
        public ParameterlessTaskMethods_NoParameterTask_Generated()
        {
            SetExecutionEnvironment();
            parameterlessTaskMethods = new ParameterlessTaskMethods();
            serializer = new Amazon.Lambda.Serialization.SystemTextJson.DefaultLambdaJsonSerializer();
        }

        /// <summary>
        /// The generated Lambda function handler for <see cref="NoParameterTask"/>
        /// </summary>
        /// <returns>Result of the Lambda function execution</returns>
        public async System.Threading.Tasks.Task NoParameterTask(Stream stream)
        {
            await parameterlessTaskMethods.NoParameterTask();
        }

        private static void SetExecutionEnvironment()
        {
            const string envName = "AWS_EXECUTION_ENV";

            var envValue = new StringBuilder();

            // If there is an existing execution environment variable add the annotations package as a suffix.
            if(!string.IsNullOrEmpty(Environment.GetEnvironmentVariable(envName)))
            {
                envValue.Append($"{Environment.GetEnvironmentVariable(envName)}_");
            }

            envValue.Append("lib/amazon-lambda-annotations#{ANNOTATIONS_ASSEMBLY_VERSION}");

            Environment.SetEnvironmentVariable(envName, envValue.ToString());
        }
    }
}
