// <auto-generated/>

using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;
using System.IO;
using Amazon.Lambda.Core;
using Amazon.Lambda.Annotations.APIGateway;

namespace TestCustomAuthorizerApp
{
    public class ProtectedFunction_GetIHttpResult_Generated
    {
        private readonly ProtectedFunction protectedFunction;
        private readonly Amazon.Lambda.Serialization.SystemTextJson.DefaultLambdaJsonSerializer serializer;

        /// <summary>
        /// Default constructor. This constructor is used by Lambda to construct the instance. When invoked in a Lambda environment
        /// the AWS credentials will come from the IAM role associated with the function and the AWS region will be set to the
        /// region the Lambda function is executed in.
        /// </summary>
        public ProtectedFunction_GetIHttpResult_Generated()
        {
            SetExecutionEnvironment();
            protectedFunction = new ProtectedFunction();
            serializer = new Amazon.Lambda.Serialization.SystemTextJson.DefaultLambdaJsonSerializer();
        }

        /// <summary>
        /// The generated Lambda function handler for <see cref="GetIHttpResult(string, string, Amazon.Lambda.Core.ILambdaContext)"/>
        /// </summary>
        /// <param name="__request__">The API Gateway request object that will be processed by the Lambda function handler.</param>
        /// <param name="__context__">The ILambdaContext that provides methods for logging and describing the Lambda environment.</param>
        /// <returns>Result of the Lambda function execution</returns>
        public System.IO.Stream GetIHttpResult(Amazon.Lambda.APIGatewayEvents.APIGatewayHttpApiV2ProxyRequest __request__, Amazon.Lambda.Core.ILambdaContext __context__)
        {
            var validationErrors = new List<string>();

            var userId = default(string);
            if (__request__.RequestContext?.Authorizer?.Lambda == null || __request__.RequestContext?.Authorizer?.Lambda.ContainsKey("userId") == false)
            {
#if NET6_0_OR_GREATER
                __context__.Logger.LogDebug("Authorizer attribute 'userId' was missing, returning unauthorized.");
#else
                __context__.Logger.Log("Authorizer attribute 'userId' was missing, returning unauthorized.");
#endif
                var __unauthorized__ = new Amazon.Lambda.APIGatewayEvents.APIGatewayHttpApiV2ProxyResponse
                {                    
                    Headers = new Dictionary<string, string>
                    {
                        {"Content-Type", "application/json"},
                        {"x-amzn-ErrorType", "AccessDeniedException"}
                    },
                    StatusCode = 401
                };
                var __unauthorizedStream__ = new System.IO.MemoryStream();
                serializer.Serialize(__unauthorized__, __unauthorizedStream__);
                __unauthorizedStream__.Position = 0;
                return __unauthorizedStream__;
            }
            
            try
            {
                var __authValue_userId__ = __request__.RequestContext.Authorizer.Lambda["userId"];
                userId = (string)Convert.ChangeType(__authValue_userId__?.ToString(), typeof(string));
            }
            catch (Exception e) when (e is InvalidCastException || e is FormatException || e is OverflowException || e is ArgumentException)
            {
#if NET6_0_OR_GREATER
                __context__.Logger.LogError(e, "Failed to convert authorizer attribute 'userId', returning unauthorized.");
#else
                __context__.Logger.Log("Failed to convert authorizer attribute 'userId', returning unauthorized. Exception: " + e.ToString());
#endif
                var __unauthorized__ = new Amazon.Lambda.APIGatewayEvents.APIGatewayHttpApiV2ProxyResponse
                {                    
                    Headers = new Dictionary<string, string>
                    {
                        {"Content-Type", "application/json"},
                        {"x-amzn-ErrorType", "AccessDeniedException"}
                    },
                    StatusCode = 401
                };
                var __unauthorizedStream__ = new System.IO.MemoryStream();
                serializer.Serialize(__unauthorized__, __unauthorizedStream__);
                __unauthorizedStream__.Position = 0;
                return __unauthorizedStream__;
            }

            var email = default(string);
            if (__request__.RequestContext?.Authorizer?.Lambda == null || __request__.RequestContext?.Authorizer?.Lambda.ContainsKey("email") == false)
            {
#if NET6_0_OR_GREATER
                __context__.Logger.LogDebug("Authorizer attribute 'email' was missing, returning unauthorized.");
#else
                __context__.Logger.Log("Authorizer attribute 'email' was missing, returning unauthorized.");
#endif
                var __unauthorized__ = new Amazon.Lambda.APIGatewayEvents.APIGatewayHttpApiV2ProxyResponse
                {                    
                    Headers = new Dictionary<string, string>
                    {
                        {"Content-Type", "application/json"},
                        {"x-amzn-ErrorType", "AccessDeniedException"}
                    },
                    StatusCode = 401
                };
                var __unauthorizedStream__ = new System.IO.MemoryStream();
                serializer.Serialize(__unauthorized__, __unauthorizedStream__);
                __unauthorizedStream__.Position = 0;
                return __unauthorizedStream__;
            }
            
            try
            {
                var __authValue_email__ = __request__.RequestContext.Authorizer.Lambda["email"];
                email = (string)Convert.ChangeType(__authValue_email__?.ToString(), typeof(string));
            }
            catch (Exception e) when (e is InvalidCastException || e is FormatException || e is OverflowException || e is ArgumentException)
            {
#if NET6_0_OR_GREATER
                __context__.Logger.LogError(e, "Failed to convert authorizer attribute 'email', returning unauthorized.");
#else
                __context__.Logger.Log("Failed to convert authorizer attribute 'email', returning unauthorized. Exception: " + e.ToString());
#endif
                var __unauthorized__ = new Amazon.Lambda.APIGatewayEvents.APIGatewayHttpApiV2ProxyResponse
                {                    
                    Headers = new Dictionary<string, string>
                    {
                        {"Content-Type", "application/json"},
                        {"x-amzn-ErrorType", "AccessDeniedException"}
                    },
                    StatusCode = 401
                };
                var __unauthorizedStream__ = new System.IO.MemoryStream();
                serializer.Serialize(__unauthorized__, __unauthorizedStream__);
                __unauthorizedStream__.Position = 0;
                return __unauthorizedStream__;
            }

            // return 400 Bad Request if there exists a validation error
            if (validationErrors.Any())
            {
                var errorResult = new Amazon.Lambda.APIGatewayEvents.APIGatewayHttpApiV2ProxyResponse
                {
                    Body = @$"{{""message"": ""{validationErrors.Count} validation error(s) detected: {string.Join(",", validationErrors)}""}}",
                    Headers = new Dictionary<string, string>
                    {
                        {"Content-Type", "application/json"},
                        {"x-amzn-ErrorType", "ValidationException"}
                    },
                    StatusCode = 400
                };
                var errorStream = new System.IO.MemoryStream();
                serializer.Serialize(errorResult, errorStream);
                errorStream.Position = 0;
                return errorStream;
            }

            var httpResults = protectedFunction.GetIHttpResult(userId, email, __context__);
            HttpResultSerializationOptions.ProtocolFormat serializationFormat = HttpResultSerializationOptions.ProtocolFormat.HttpApi;
            HttpResultSerializationOptions.ProtocolVersion serializationVersion = HttpResultSerializationOptions.ProtocolVersion.V2;
            var serializationOptions = new HttpResultSerializationOptions { Format = serializationFormat, Version = serializationVersion, Serializer = serializer };
            var response = httpResults.Serialize(serializationOptions);
            return response;
        }

        private static void SetExecutionEnvironment()
        {
            const string envName = "AWS_EXECUTION_ENV";

            var envValue = new StringBuilder();

            // If there is an existing execution environment variable add the annotations package as a suffix.
            if(!string.IsNullOrEmpty(Environment.GetEnvironmentVariable(envName)))
            {
                envValue.Append($"{Environment.GetEnvironmentVariable(envName)}_");
            }

            envValue.Append("lib/amazon-lambda-annotations#{ANNOTATIONS_ASSEMBLY_VERSION}");

            Environment.SetEnvironmentVariable(envName, envValue.ToString());
        }
    }
}