// <auto-generated/>

using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;
using System.IO;
using Amazon.Lambda.Core;

namespace TestCustomAuthorizerApp
{
    public class ProtectedFunction_GetHttpApiV1UserInfo_Generated
    {
        private readonly ProtectedFunction protectedFunction;
        private readonly Amazon.Lambda.Serialization.SystemTextJson.DefaultLambdaJsonSerializer serializer;

        /// <summary>
        /// Default constructor. This constructor is used by Lambda to construct the instance. When invoked in a Lambda environment
        /// the AWS credentials will come from the IAM role associated with the function and the AWS region will be set to the
        /// region the Lambda function is executed in.
        /// </summary>
        public ProtectedFunction_GetHttpApiV1UserInfo_Generated()
        {
            SetExecutionEnvironment();
            protectedFunction = new ProtectedFunction();
            serializer = new Amazon.Lambda.Serialization.SystemTextJson.DefaultLambdaJsonSerializer();
        }

        /// <summary>
        /// The generated Lambda function handler for <see cref="GetHttpApiV1UserInfo(string, string, string, Amazon.Lambda.Core.ILambdaContext)"/>
        /// </summary>
        /// <param name="__request__">The API Gateway request object that will be processed by the Lambda function handler.</param>
        /// <param name="__context__">The ILambdaContext that provides methods for logging and describing the Lambda environment.</param>
        /// <returns>Result of the Lambda function execution</returns>
        public Amazon.Lambda.APIGatewayEvents.APIGatewayProxyResponse GetHttpApiV1UserInfo(Amazon.Lambda.APIGatewayEvents.APIGatewayProxyRequest __request__, Amazon.Lambda.Core.ILambdaContext __context__)
        {
            var validationErrors = new List<string>();

            var userId = default(string);
            if (__request__.RequestContext?.Authorizer == null || __request__.RequestContext?.Authorizer.ContainsKey("userId") == false)
            {
#if NET6_0_OR_GREATER
                __context__.Logger.LogDebug("Authorizer attribute 'userId' was missing, returning unauthorized.");
#else
                __context__.Logger.Log("Authorizer attribute 'userId' was missing, returning unauthorized.");
#endif
                var __unauthorized__ = new Amazon.Lambda.APIGatewayEvents.APIGatewayProxyResponse
                {                    
                    Headers = new Dictionary<string, string>
                    {
                        {"Content-Type", "application/json"},
                        {"x-amzn-ErrorType", "AccessDeniedException"}
                    },
                    StatusCode = 401
                };
                return __unauthorized__;
            }
            
            try
            {
                var __authValue_userId__ = __request__.RequestContext.Authorizer["userId"];
                userId = (string)Convert.ChangeType(__authValue_userId__?.ToString(), typeof(string));
            }
            catch (Exception e) when (e is InvalidCastException || e is FormatException || e is OverflowException || e is ArgumentException)
            {
#if NET6_0_OR_GREATER
                __context__.Logger.LogError(e, "Failed to convert authorizer attribute 'userId', returning unauthorized.");
#else
                __context__.Logger.Log("Failed to convert authorizer attribute 'userId', returning unauthorized. Exception: " + e.ToString());
#endif
                var __unauthorized__ = new Amazon.Lambda.APIGatewayEvents.APIGatewayProxyResponse
                {                    
                    Headers = new Dictionary<string, string>
                    {
                        {"Content-Type", "application/json"},
                        {"x-amzn-ErrorType", "AccessDeniedException"}
                    },
                    StatusCode = 401
                };
                return __unauthorized__;
            }

            var email = default(string);
            if (__request__.RequestContext?.Authorizer == null || __request__.RequestContext?.Authorizer.ContainsKey("email") == false)
            {
#if NET6_0_OR_GREATER
                __context__.Logger.LogDebug("Authorizer attribute 'email' was missing, returning unauthorized.");
#else
                __context__.Logger.Log("Authorizer attribute 'email' was missing, returning unauthorized.");
#endif
                var __unauthorized__ = new Amazon.Lambda.APIGatewayEvents.APIGatewayProxyResponse
                {                    
                    Headers = new Dictionary<string, string>
                    {
                        {"Content-Type", "application/json"},
                        {"x-amzn-ErrorType", "AccessDeniedException"}
                    },
                    StatusCode = 401
                };
                return __unauthorized__;
            }
            
            try
            {
                var __authValue_email__ = __request__.RequestContext.Authorizer["email"];
                email = (string)Convert.ChangeType(__authValue_email__?.ToString(), typeof(string));
            }
            catch (Exception e) when (e is InvalidCastException || e is FormatException || e is OverflowException || e is ArgumentException)
            {
#if NET6_0_OR_GREATER
                __context__.Logger.LogError(e, "Failed to convert authorizer attribute 'email', returning unauthorized.");
#else
                __context__.Logger.Log("Failed to convert authorizer attribute 'email', returning unauthorized. Exception: " + e.ToString());
#endif
                var __unauthorized__ = new Amazon.Lambda.APIGatewayEvents.APIGatewayProxyResponse
                {                    
                    Headers = new Dictionary<string, string>
                    {
                        {"Content-Type", "application/json"},
                        {"x-amzn-ErrorType", "AccessDeniedException"}
                    },
                    StatusCode = 401
                };
                return __unauthorized__;
            }

            var tenantId = default(string);
            if (__request__.RequestContext?.Authorizer == null || __request__.RequestContext?.Authorizer.ContainsKey("tenantId") == false)
            {
#if NET6_0_OR_GREATER
                __context__.Logger.LogDebug("Authorizer attribute 'tenantId' was missing, returning unauthorized.");
#else
                __context__.Logger.Log("Authorizer attribute 'tenantId' was missing, returning unauthorized.");
#endif
                var __unauthorized__ = new Amazon.Lambda.APIGatewayEvents.APIGatewayProxyResponse
                {                    
                    Headers = new Dictionary<string, string>
                    {
                        {"Content-Type", "application/json"},
                        {"x-amzn-ErrorType", "AccessDeniedException"}
                    },
                    StatusCode = 401
                };
                return __unauthorized__;
            }
            
            try
            {
                var __authValue_tenantId__ = __request__.RequestContext.Authorizer["tenantId"];
                tenantId = (string)Convert.ChangeType(__authValue_tenantId__?.ToString(), typeof(string));
            }
            catch (Exception e) when (e is InvalidCastException || e is FormatException || e is OverflowException || e is ArgumentException)
            {
#if NET6_0_OR_GREATER
                __context__.Logger.LogError(e, "Failed to convert authorizer attribute 'tenantId', returning unauthorized.");
#else
                __context__.Logger.Log("Failed to convert authorizer attribute 'tenantId', returning unauthorized. Exception: " + e.ToString());
#endif
                var __unauthorized__ = new Amazon.Lambda.APIGatewayEvents.APIGatewayProxyResponse
                {                    
                    Headers = new Dictionary<string, string>
                    {
                        {"Content-Type", "application/json"},
                        {"x-amzn-ErrorType", "AccessDeniedException"}
                    },
                    StatusCode = 401
                };
                return __unauthorized__;
            }

            // return 400 Bad Request if there exists a validation error
            if (validationErrors.Any())
            {
                var errorResult = new Amazon.Lambda.APIGatewayEvents.APIGatewayProxyResponse
                {
                    Body = @$"{{""message"": ""{validationErrors.Count} validation error(s) detected: {string.Join(",", validationErrors)}""}}",
                    Headers = new Dictionary<string, string>
                    {
                        {"Content-Type", "application/json"},
                        {"x-amzn-ErrorType", "ValidationException"}
                    },
                    StatusCode = 400
                };
                return errorResult;
            }

            var response = protectedFunction.GetHttpApiV1UserInfo(userId, email, tenantId, __context__);
            var memoryStream = new MemoryStream();
            serializer.Serialize(response, memoryStream);
            memoryStream.Position = 0;

            // convert stream to string
            StreamReader reader = new StreamReader( memoryStream );
            var body = reader.ReadToEnd();

            return new Amazon.Lambda.APIGatewayEvents.APIGatewayProxyResponse
            {
                Body = body,
                Headers = new Dictionary<string, string>
                {
                    {"Content-Type", "application/json"}
                },
                StatusCode = 200
            };
        }

        private static void SetExecutionEnvironment()
        {
            const string envName = "AWS_EXECUTION_ENV";

            var envValue = new StringBuilder();

            // If there is an existing execution environment variable add the annotations package as a suffix.
            if(!string.IsNullOrEmpty(Environment.GetEnvironmentVariable(envName)))
            {
                envValue.Append($"{Environment.GetEnvironmentVariable(envName)}_");
            }

            envValue.Append("lib/amazon-lambda-annotations#{ANNOTATIONS_ASSEMBLY_VERSION}");

            Environment.SetEnvironmentVariable(envName, envValue.ToString());
        }
    }
}