// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

using System.Linq;
using System.Text;
using Amazon.Lambda.Model;
using Xunit;
using Xunit.Abstractions;

namespace Amazon.Lambda.DurableExecution.IntegrationTests;

/// <summary>
/// Proves a durable function works end-to-end through the <b>Lambda Annotations programming model in the
/// class-library variant</b>: a method annotated with <c>[LambdaFunction]</c> + <c>[DurableExecution]</c>
/// but with NO <c>GenerateMain</c>, so the source generator emits only the handler wrapper (no
/// <c>Program.g.cs</c>) and the managed runtime invokes it via an <c>Assembly::Type::Method</c> handler.
/// The generated wrapper delegates to the same <c>DurableFunction.WrapAsync</c> entry point as every other
/// model, so checkpointing behavior is identical and this reuses the canonical two-step assertion shape
/// (see <see cref="ClassLibraryTest"/>). The executable variant of this Annotations path is covered at the
/// generator level by the <c>DurableExecutionE2ETests</c> snapshot tests in the source-generator test project.
/// </summary>
/// <remarks>
/// Deployed via an <c>Assembly::Type::Method</c> handler string — the same class-library deployment shape as
/// the hand-written <see cref="ClassLibraryTest"/>, but here the wrapper type
/// (<c>Function_Workflow_Generated</c>) is generated by the Annotations source generator rather than
/// hand-written. No <c>ANNOTATIONS_HANDLER</c> env var is needed (that is the executable model's dispatch
/// mechanism).
/// </remarks>
public class AnnotationsClassLibraryTest
{
    private readonly ITestOutputHelper _output;
    public AnnotationsClassLibraryTest(ITestOutputHelper output) => _output = output;

    [Fact]
    public async Task AnnotationsClassLibrary_TwoSteps_Checkpointed()
    {
        await using var deployment = await DurableFunctionDeployment.CreateAsync(
            DurableFunctionDeployment.FindTestFunctionDir("AnnotationsClassLibraryFunction"),
            "annotcl", _output,
            // Class-library model: the generator emits the wrapper type Function_Workflow_Generated; deploy
            // against it with an Assembly::Type::Method handler (no ANNOTATIONS_HANDLER env var).
            handler: "AnnotationsClassLibraryFunction::AnnotationsClassLibraryFunction.Function_Workflow_Generated::Workflow");

        var (invokeResponse, executionName) = await deployment.InvokeAsync("""{"orderId": "chain"}""");
        Assert.Equal(200, invokeResponse.StatusCode);

        var responsePayload = Encoding.UTF8.GetString(invokeResponse.Payload.ToArray());
        _output.WriteLine($"Response: {responsePayload}");

        var arn = await deployment.FindDurableExecutionArnByNameAsync(executionName, TimeSpan.FromSeconds(60));
        Assert.NotNull(arn);

        var status = await deployment.PollForCompletionAsync(arn!, TimeSpan.FromSeconds(60));
        Assert.Equal("SUCCEEDED", status, ignoreCase: true);

        // History is eventually consistent — wait until both steps are indexed.
        var history = await deployment.WaitForHistoryAsync(
            arn!,
            h => (h.Events?.Count(e => e.EventType == EventType.StepStarted) ?? 0) >= 2
              && (h.Events?.Count(e => e.StepSucceededDetails != null) ?? 0) >= 2,
            TimeSpan.FromSeconds(60));
        var events = history.Events ?? new List<Event>();

        // Both steps ran exactly once, in declaration order, each chaining from the previous one's output —
        // same checkpointing behavior the hand-written and executable models produce.
        Assert.Equal(2, events.Count(e => e.EventType == EventType.StepStarted));

        var stepResults = events
            .Where(e => e.StepSucceededDetails != null)
            .Select(e => $"{e.Name}={e.StepSucceededDetails.Result?.Payload?.Trim('"')}")
            .ToList();
        Assert.Equal(
            new[]
            {
                "step_1=a-chain",
                "step_2=a-chain-b",
            },
            stepResults);
    }
}
