version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 3.1
  pre_build:
    commands:
      - yum install tar --assumeyes
      - yum install gzip --assumeyes
      - curl -sSL https://dot.net/v1/dotnet-install.sh --output dotnet-install.sh
      - chmod +x dotnet-install.sh
      - source ./dotnet-install.sh --version 5.0.100
  build:
    commands:
      - pwsh LambdaRuntimeDockerfiles/dotnet5/Infrastructure/src/Infrastructure/SmokeTests/build.ps1
        -SourceEcr $AWS_LAMBDA_SOURCE_ECR
        -EcrRepositoryName $AWS_LAMBDA_ECR_REPOSITORY_NAME
        -SourceImageTag $CODEBUILD_RESOLVED_SOURCE_VERSION
