name: Build Lambda Runtime Images

on:
  pull_request:
    paths:
      - "LambdaRuntimeDockerfiles/**"
  push:
    paths:
      - "LambdaRuntimeDockerfiles/**"

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-runtime-images:
    name: Build runtime image (${{ matrix.name }})
    runs-on: ubuntu-latest
    permissions:
      contents: read # to check out the repository and build the Dockerfiles
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: NET 8 AMD64
            dockerfile: LambdaRuntimeDockerfiles/Images/net8/amd64/Dockerfile
            platform: linux/amd64
          - name: NET 8 ARM64
            dockerfile: LambdaRuntimeDockerfiles/Images/net8/arm64/Dockerfile
            platform: linux/arm64
          - name: NET 9 AMD64
            dockerfile: LambdaRuntimeDockerfiles/Images/net9/amd64/Dockerfile
            platform: linux/amd64
          - name: NET 9 ARM64
            dockerfile: LambdaRuntimeDockerfiles/Images/net9/arm64/Dockerfile
            platform: linux/arm64
          - name: NET 10 AMD64
            dockerfile: LambdaRuntimeDockerfiles/Images/net10/amd64/Dockerfile
            platform: linux/amd64
          - name: NET 10 ARM64
            dockerfile: LambdaRuntimeDockerfiles/Images/net10/arm64/Dockerfile
            platform: linux/arm64
          - name: NET 11 AMD64
            dockerfile: LambdaRuntimeDockerfiles/Images/net11/amd64/Dockerfile
            platform: linux/amd64
          - name: NET 11 ARM64
            dockerfile: LambdaRuntimeDockerfiles/Images/net11/arm64/Dockerfile
            platform: linux/arm64

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4

      - name: Build ${{ matrix.name }}
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: ${{ matrix.platform }}
          push: false
          provenance: false

