"on":
  issues:
    types:
    - opened
    - edited
name: issue-regression-label
jobs:
  add-regression-label:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
    - id: check_regression
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea
      with:
        script: |
          const regressionPattern = /\[x\] Select this option if this issue appears to be a regression\./i;
          const template = `${process.env.TEMPLATE_BODY}`
          const match = regressionPattern.test(template);
          core.setOutput('is_regression', match);
      name: Fetch template body
      env:
        TEMPLATE_BODY: ${{ github.event.issue.body }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        if [ "${{ steps.check_regression.outputs.is_regression }}" == "true" ]; then
          gh issue edit ${{ github.event.issue.number }} --add-label "potential-regression" -R ${{ github.repository }}
        else
          gh issue edit ${{ github.event.issue.number }} --remove-label "potential-regression" -R ${{ github.repository }}
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Manage regression label
