"on":
  push:
    branches:
    - dev
    - main
  schedule:
  - cron: 23 20 * * 1
  workflow_dispatch: 
  pull_request: 
name: Semgrep
jobs:
  semgrep:
    if: (github.actor != 'dependabot[bot]')
    container:
      image: returntocorp/semgrep
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - run: semgrep ci --sarif > semgrep.sarif
      env:
        SEMGREP_RULES: p/security-audit p/secrets p/owasp-top-ten
    - uses: github/codeql-action/upload-sarif@v2
      if: always()
      name: Upload SARIF file for GitHub Advanced Security Dashboard
      with:
        sarif_file: semgrep.sarif
    name: Scan
