name: Semgrep

on:
  # Scan changed files in PRs, block on new issues only (existing issues ignored)
  pull_request:

  push:
    branches: ["dev", "master"]

  schedule:
    - cron: '23 20 * * 1'

  # Manually trigger the workflow
  workflow_dispatch:

jobs:
  semgrep:
    name: Scan
    permissions:
      security-events: write
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    # Skip any PR created by dependabot to avoid permission issues
    if: (github.actor != 'dependabot[bot]')
    steps:
      # Fetch project source
      - uses: actions/checkout@v4

      - run: semgrep ci --sarif > semgrep.sarif
        env:
          SEMGREP_RULES: >- # more at semgrep.dev/explore
            p/security-audit
            p/secrets
            p/owasp-top-ten

      - name: Upload SARIF file for GitHub Advanced Security Dashboard
        uses: github/codeql-action/upload-sarif@60168efe1c415ce0f5521ea06d5c2062adbeed1b #v3.28.17
        with:
          sarif_file: semgrep.sarif
        if: always()
