"on":
  schedule:
  - cron: 0 0 * * *
name: Close stale issues
jobs:
  cleanup:
    runs-on: ubuntu-latest
    name: Stale issue job
    steps:
    - uses: aws-actions/stale-issue-cleanup@7de35968489e4142233d2a6812519a82e68b5c38
      with:
        stale-issue-label: closing-soon
        stale-issue-message: This issue has not received a response in 5 days. If you want to keep this issue open, please just leave a comment below and auto-close will be canceled.
        days-before-ancient: 36500
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-pr-label: no-pr-activity
        exempt-issue-labels: no-autoclose
        ancient-issue-message: We have noticed this issue has not received attention in 1 year. We will close this issue for now. If you think this is in error, please feel free to comment and reopen the issue.
        minimum-upvotes-to-exempt: 10
        response-requested-label: response-requested
        days-before-close: 4
        exempt-pr-labels: awaiting-approval
        closed-for-staleness-label: closed-for-staleness
        days-before-stale: 10
